# Generated by Django 5.2.1 on 2025-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='store.category'),
        ),
    ]
